const Icons = {
    quivio_img:require('./icons/quivio.png'),
    img1:require('./icons/img1.png'),
    img2:require('./icons/img2.png'),
    img3:require('./icons/img3.png'),
    bigheader:require('./icons/bigheader.png'),
    logo:require('./icons/logo.png'),
    textquivio:require('./icons/textquivio.png'),
    hortlist:require('./icons/horilist.png'),
    line:require('./icons/line.png'),
    asethetical:require('./icons/asethetical.png'),
    real:require('./icons/real.png'),
    track:require('./icons/track.png'),
    mail:require('./icons/mail.png'),
    lock:require('./icons/lock.png'),
    eyeopen:require('./icons/eyeopen.png'),
    left:require('./icons/left.png'),
    errormail:require('./icons/errormail.png'),
    errorlock:require('./icons/errorlock.png'),
    collen:require('./icons/collen.png'),
    lockopen:require('./icons/lockopen.png'),
    toss:require('./icons/toss.png'),
    linksend:require('./icons/linksend.png'),
    quiviologo:require('./icons/quiviologo.png'),
    cross:require('./icons/cross.png'),
    right:require('./icons/right.png'),
    twofactor:require('./icons/twofactor.png'),
    status:require('./icons/status.png'),
    settings:require('./icons/settings.png'),
    announcement:require('./icons/annoucement.png'),
    message:require('./icons/message.png'),
    bell:require('./icons/bell.png'),
    verified:require('./icons/verified.png'),
    faild:require('./icons/failed.png'),
    exist:require('./icons/exist.png'),
    splash:require('./icons/splash.png'),
    eyeclose:require('./icons/eyeclose.png'),
    homeicon:require('./icons/homeicon.png'),
    account:require('./icons/account.png'),
    star:require('./icons/star.png'),
    menu:require('./icons/menu.png'),
    avatar:require('./icons/avatar.png'),
    callender:require('./icons/callender.png'),
    camera:require('./icons/camera.png'),
    dropdown:require('./icons/dropdown.png'),
    forward:require('./icons/forward.png'),
    image:require('./icons/image.png'),
    profile:require('./icons/profile.png'),
    upload:require('./icons/upload.png'),





    

  };
  export {Icons}